### ISSUE TITLE
Check viability of using the waterfall function to coordinate API calls

### ISSUE THREAD

**Issue by PiotrBerebecki** [FAC10/week3-jzlp#11]

**Comment by lucyrose93** [comment]
Let's put anything interesting/useful we find in comments below... @PiotrBerebecki

**Comment by lucyrose93** [comment]
async-waterfall https://www.npmjs.com/package/async-waterfall
Technically using this would defeat the purpose of this project. But it may be useful for future ref.

**Comment by lucyrose93** [comment]
`
fetch function(){
  //do the api request
}

function getLocation(x, cb) { 
  //this is where you pass the url to your fetch function, which returns locationObject, then you extract data 
    return cb(null, x + 'location'); 
  }

function getWeather(x, cb) {
    return cb(null, x + 'weather');
  }

function getGif(x, cb) {
    return cb(null, x + 'gif');
  }


//define waterfall function

function waterfall(arg, tasks, cb) {

  if(tasks.length>0){ //i.e. if there are still tasks to complete
    tasks[0](arg, function(error, result){ //call the first function in the tasks array
    tasks.shift(); //remove that function from the array tasks
    return waterfall(result, tasks, cb) //repeat waterfall passing result from previous function
    });
  }
  else {
    cb(null, arg) //once there are no tasks left to complete, call cb (see below)
  }
}

//call the waterfall function

waterfall('process', [
  getLocation,
  getWeather,
  getGif
],

//cb below
function(error, result) {
  console.log(result); 
});
`

**Comment by lucyrose93** [comment]
```
fetch function(){
  //do the api request
}

function getLocation(x, cb) { 
  //this is where you pass the url to your fetch function, which returns locationObject, then you extract data 
    return cb(null, x + 'location'); 
  }

function getWeather(x, cb) {
    return cb(null, x + 'weather');
  }

function getGif(x, cb) {
    return cb(null, x + 'gif');
  }


//define waterfall function

function waterfall(arg, tasks, cb) {

  if(tasks.length>0){ //i.e. if there are still tasks to complete
    tasks[0](arg, function(error, result){ //call the first function in the tasks array
    tasks.shift(); //remove that function from the array tasks
    return waterfall(result, tasks, cb) //repeat waterfall passing result from previous function
    });
  }
  else {
    cb(null, arg) //once there are no tasks left to complete, call cb (see below)
  }
}

//call the waterfall function

waterfall('process', [
  getLocation,
  getWeather,
  getGif
],

//cb below
function(error, result) {
  console.log(result); 
});

```

**Comment by lucyrose93** [comment]
See basic logic above
