### ISSUE TITLE
Be able to change our IP addresses for the presentation

### ISSUE THREAD

**Issue by lucyrose93** [FAC10/week3-jzlp#28]
In order to demo how our product works for users in different locations, we should work out how to change our IP address.

**Comment by ZooeyMiller** [comment]
We're going to use [ZenMate](https://zenmate.co.uk/). 
This is a chrome extension which allows you change your IP address on the fly (only  to 4 different locations on the free version, but this is probably enough to demonstrate that it works). :sparkles:

**Comment by lucyrose93** [comment]
Fantastic. 
That should be enough.
