### ISSUE TITLE
Add user interface

### ISSUE THREAD

**Issue by PiotrBerebecki** [FAC10/week3-jzlp#33]
Make app more user friendly

**Comment by lucyrose93** [comment]
Design inspiration... 

![image](https://cloud.githubusercontent.com/assets/15314681/23750894/e7c099b4-04c6-11e7-843c-725653d94ca5.png)

**Comment by lucyrose93** [comment]
![image](https://cloud.githubusercontent.com/assets/15314681/23750921/00419a6a-04c7-11e7-9e9e-034864fb823b.png)

**Comment by lucyrose93** [comment]
![image](https://cloud.githubusercontent.com/assets/15314681/23750930/0e03d3d4-04c7-11e7-826b-a7dbba80e6ce.png)
